bp_net_obj = {
    name : null,
    cpname : null,
    gcor : null,
    next_patno : null,
    next_epochno : null,
    pools : null,
    pools_by_name : null,
    environment : null,
    train_options: {
        "nepochs" : 100,
        "ncycles" : 50,
        "lflag" : 1,
        "lrate" : 0.5, 
        "follow" : 0,
        "cascade" : 0,
        "ecrit" : 0,
        "crate" : 0.05,
        "wrange" : 1,
        "lgrain" : "pattern",
        "errmeas" : "sse",
        "wdecay" : 0.0,
        "lgrainsize" : 1,
        "momentum" : 0.9,
        "mu" : 0.5,
        "tmax" : 1,
        "clearval" : 0.5,
        "fastrun" : 0,
        "trainset" : "none",
        "annealsched" : [],
        "temp" : 1,
        "epochno" : 0,
        "noise" : 0
    },
    test_options: {
                      "nepochs" : 100,
                      "ncycles" : 50,
                      "lflag" : 0,
                      "cascade" : 0,
                      "ecrit" : 0,
                      "crate" : 0.05,
                      "mu" : 0.5,
                      "tmax" : 1,
                      "errmeas" : "sse",
                      "wdecay" : 0,
                      "clearval" : 0.5,
                      "lrate" : 0.5,
                      "lgrain" : "pattern",
                      "lgrainsize" : 1,
                      "momentum" : 0.9,
                      "fastrun" : 0,
                      "testset" : "none",
                      "noise" : 0
                  },
    app_data : {
                   "history" : [],
                   "lognetwork" : 1,
                   "logfilename" : [],
                   "dispobjects" : [],
                   "annoteobjects" : [],
                   "templatesize" : [],
                   "cellsize" : []
               },
    seed : null,
    manual_bias : false,
    pss : 0,
    pce : 0,
    tss : 0,
    tce : 0,
    css : 0,
    nancolor : [0.97, 0.97, 0.97]
}
